#!/bin/bash
sudo archlinux-java set java-7-openjdk
if [ "$1" == local ]
then
#  cp pom-local.xml pom.xml
  mvn -f pom-local.xml clean install -Dmaven.test.skip=true -U
  sudo archlinux-java set java-8-openjdk
  java -jar target/*.war
elif [ "$1" == websphere ]
then
#  cp pom-websphere.xml pom.xml
  mvn -f pom-websphere.xml clean install -Dmaven.test.skip=true -U
fi
sudo archlinux-java set java-8-openjdk

