client:
  default-uri: http://localhost:9090/uv/ws/rnc

server:
  port: 9090

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    platform: postgres
#    url: jdbc:postgresql://localhost:5432/rnc_bd
    dbCreate: none
    jndiName: "java:comp/env/jdbc/rnc"
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
